version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: thursday
      time: "09:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5
    commit-message:
      prefix: "[Chore] "
    cooldown:
      default-days: 3
    groups:
      github-actions:
        patterns: ["*"]
  - package-ecosystem: gitsubmodule
    directory: "/"
    schedule:
      interval: weekly
      day: thursday
      time: "09:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5
    commit-message:
      prefix: "[Chore] "
    cooldown:
      default-days: 3
    groups:
      gitsubmodule:
        patterns: ["*"]
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: thursday
      time: "09:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5
    commit-message:
      prefix: "[Chore] "
    cooldown:
      default-days: 3
    groups:
      pip-minor-patch:
        update-types: ["minor", "patch"]
