sonar.projectKey=Team-Haruki_sekai-deck-recommend-cpp
sonar.organization=team-haruki
sonar.sourceEncoding=UTF-8
sonar.sources=src,tools/bench,CMakeLists.txt,.github/workflows
sonar.tests=tests
sonar.exclusions=3rdparty/**
sonar.python.version=3.10,3.11,3.12,3.13,3.14
sonar.python.coverage.reportPaths=coverage-reports/python-coverage.xml
sonar.coverageReportPaths=coverage-reports/cpp-coverage.xml
sonar.cfamily.reportingCppStandardOverride=c++20
