name: Build sdist

on:
  workflow_call:

jobs:
  sdist:
    name: sdist
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: "3.11"

      - name: Set up uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          version: "0.9.18"
          enable-cache: true

      - name: Install build package
        run: uv pip install --system build

      - name: Build sdist
        run: python -m build --sdist

      - name: Upload sdist artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: pypi-sdist
          path: dist/*.tar.gz
